/**
 * SEO/GEO helpers for the BOOK-side entity pages.
 *
 * TypeScript port of the book-relevant parts of ../app/core/seo.py:
 *   - slugify
 *   - JSON-LD builders: book_jsonld, breadcrumb_jsonld, faq_jsonld,
 *     qa_page_jsonld, insights_article_jsonld
 *   - detect_capabilities
 *
 * Plus data-fetch helpers (getBookData / getQuestions / getSamplePassages /
 * getInsights) that wrap the FastAPI JSON API with graceful degradation —
 * every call swallows errors and returns an empty/neutral value so the SSR
 * pages never crash when the API is down or an entity is missing.
 *
 * Escaping note: the Python originals build escaped HTML strings; here the
 * JSON-LD builders return plain objects and section rendering lives in React
 * components. JSX escapes text by default and <JsonLd> JSON.stringifies, so
 * we do NOT html-escape here.
 */

import { get } from "@/lib/api";

export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://feynman.wiki";

// ─── Slug generation (ported from seo.py slugify) ──────────────────────

const SLUG_NON_ALNUM = /[^a-z0-9]+/g;
const SLUG_TRIM = /^-+|-+$/g;

/**
 * Convert a title or name into a URL-safe kebab-case slug. Deterministic
 * and ASCII-only — must match the Python `slugify` so URLs generated by the
 * FastAPI sitemap and these Next pages resolve identically.
 */
export function slugify(text: string, maxLen = 80): string {
  if (!text) return "untitled";
  let s = text.toLowerCase().trim();
  // Best-effort ASCII fold: decompose accents and drop combining marks
  // (mirrors Python's `.encode("ascii","ignore")`). The SLUG_NON_ALNUM pass
  // then collapses every remaining non-[a-z0-9] char — including any
  // surviving high-Unicode codepoints — to dashes, so a separate non-ASCII
  // strip is unnecessary.
  s = s.normalize("NFKD").replace(/\p{M}/gu, "");
  s = s.replace(SLUG_NON_ALNUM, "-");
  s = s.replace(SLUG_TRIM, "");
  if (!s) return "untitled";
  if (s.length > maxLen) {
    const cut = s.slice(0, maxLen);
    const lastDash = cut.lastIndexOf("-");
    s = lastDash > 0 ? cut.slice(0, lastDash) : cut;
  }
  return s;
}

/** Match a URL slug back to the original question text (linear scan). */
export function findQuestionBySlug(
  questions: string[],
  slug: string,
): string | null {
  if (!questions?.length || !slug) return null;
  const target = slug.trim().toLowerCase();
  for (const q of questions) {
    if (slugify(q) === target) return q;
  }
  return null;
}

/**
 * The 5 generic fallback questions the backend inserts when book-specific
 * question generation fails. They are byte-identical across ~400 books, so
 * their /q pages duplicate one another ("Duplicate without user-selected
 * canonical" in GSC) and aren't real search queries — keep them OUT of the
 * index regardless of whether a grounded answer exists. (Regenerating
 * book-specific questions is the eventual fix; until then, noindex.) Keep in
 * sync with GENERIC_FALLBACK_QUESTIONS in app/core/seo.py.
 */
export const GENERIC_FALLBACK_QUESTIONS: ReadonlySet<string> = new Set([
  "What is the central thesis of this text?",
  "What evidence does the author provide?",
  "How would you explain the key concepts in your own words?",
  "What are the practical implications?",
  "What questions remain unanswered?",
]);

export function isGenericFallbackQuestion(q: string): boolean {
  return GENERIC_FALLBACK_QUESTIONS.has((q || "").trim());
}

/**
 * Map a book's free-form `meta.category` to one of the 15 canonical topic
 * hubs, so the "More on …" link resolves to a real /topic/{slug} (200) instead
 * of 404'ing. Books carry 46+ ad-hoc categories ("Business" vs the canonical
 * "Business & Strategy", plus "Chemistry", "Contemporary Fiction", and some
 * leaked chat prompts) — only those that map to a canonical topic get a link;
 * the rest return null and the caller omits the link rather than sending a
 * crawler to a dead end. `topics` is the canonical list from /api/topics.
 */
export function canonicalTopicForCategory(
  category: string,
  topics: string[],
): string | null {
  const cat = (category || "").trim().toLowerCase();
  if (!cat || !topics?.length) return null;
  const catSlug = slugify(category);
  // 1) exact slug match (Psychology, Economics, Computer Science, …)
  for (const t of topics) {
    if (slugify(t) === catSlug) return t;
  }
  // 2) loose containment either way (Business → Business & Strategy)
  for (const t of topics) {
    const tl = t.toLowerCase();
    if (tl.includes(cat) || cat.includes(tl)) return t;
  }
  return null;
}

/**
 * Whether a book's `meta.category` is a real, displayable category rather than
 * a leaked chat query. Topic-discovery stored the user's raw prompt as the
 * category for ~50 books ("how game theory can be used in hiring", "who are
 * you", CJK queries). Those are real books we keep indexed — we just must not
 * render the junk as "Book · {category}". Real categories are short,
 * Title-Case and ASCII; chat queries start lowercase / non-Latin, run long, or
 * are questions.
 */
export function isCleanCategory(category: string): boolean {
  const c = (category || "").trim();
  if (!c || c.includes("?")) return false;
  if (!/^[A-Z]/.test(c)) return false; // Title-Case ASCII; chat queries / CJK aren't
  if (c.split(/\s+/).length > 4) return false; // real categories are short
  if (/^(How|What|Who|Why|Does|Is|Are|Should|Can|Will|We|My)\b/.test(c)) return false;
  return true;
}

// ─── JSON-LD schema builders (ported from seo.py) ──────────────────────

type Json = Record<string, unknown>;

/** Drop null/empty leaves so schema validators don't choke (port of _drop_nulls). */
function dropNulls<T>(obj: T): T {
  if (Array.isArray(obj)) {
    return obj.map((x) => dropNulls(x)) as unknown as T;
  }
  if (obj && typeof obj === "object") {
    const out: Json = {};
    for (const [k, v] of Object.entries(obj as Json)) {
      const cleaned = dropNulls(v);
      const isEmpty =
        cleaned === null ||
        cleaned === undefined ||
        cleaned === "" ||
        (Array.isArray(cleaned) && cleaned.length === 0);
      if (!isEmpty) out[k] = cleaned;
    }
    return out as unknown as T;
  }
  return obj;
}

export interface BreadcrumbItem {
  name: string;
  url: string;
}

/** BreadcrumbList schema. `items` is root-first, current-page-last. */
export function breadcrumbJsonld(items: BreadcrumbItem[]): Json {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      item: it.url,
    })),
  };
}

export interface QaPair {
  question: string;
  answer: string;
}

/** FAQPage schema. Answers must be non-empty per Google's spec. */
export function faqJsonld(qaPairs: QaPair[]): Json {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: qaPairs.map((qa) => ({
      "@type": "Question",
      name: qa.question,
      acceptedAnswer: { "@type": "Answer", text: qa.answer },
    })),
  };
}

export interface Chapter {
  title?: string;
  number?: number;
}

export interface BookJsonldArgs {
  title: string;
  description: string;
  author: string;
  url: string;
  image: string;
  wordCount?: number | null;
  chapters?: Chapter[] | null;
  siteUrl: string;
  inLanguage?: string;
  datePublished?: string;
  dateModified?: string;
}

/**
 * Schema.org/Book — omits numberOfPages (we have no physical pages);
 * chapter structure goes in hasPart. Result is run through dropNulls for
 * parity with the Python jsonld_script wrapper.
 */
export function bookJsonld(args: BookJsonldArgs): Json {
  const out: Json = {
    "@context": "https://schema.org",
    "@type": "Book",
    name: args.title,
    description: args.description,
    url: args.url,
    image: args.image,
    inLanguage: args.inLanguage || "en",
    publisher: { "@type": "Organization", name: "Feynman", url: args.siteUrl },
  };
  if (args.author) out.author = { "@type": "Person", name: args.author };
  if (args.wordCount) out.wordCount = args.wordCount;
  if (args.chapters && args.chapters.length) {
    out.hasPart = args.chapters.map((c, i) => ({
      "@type": "Chapter",
      name: c.title || "",
      position: i + 1,
    }));
  }
  if (args.datePublished) out.datePublished = args.datePublished;
  if (args.dateModified) out.dateModified = args.dateModified;
  return dropNulls(out);
}

export interface QaPageJsonldArgs {
  question: string;
  answer: string;
  url: string;
  bookTitle: string;
  bookUrl: string;
  siteUrl?: string;
  dateCreated?: string;
}

/**
 * Schema.org/QAPage with all Google-required fields (name, text,
 * answerCount, acceptedAnswer). Falls back to a chat-deflection answer when
 * no synthesized answer is available (non-empty is required).
 */
export function qaPageJsonld(args: QaPageJsonldArgs): Json {
  let answerText = (args.answer || "").trim();
  if (!answerText) {
    answerText = `Open Feynman to chat with the book "${args.bookTitle}" and explore the answer in depth: ${args.bookUrl}`;
  }
  const author: Json = { "@type": "Organization", name: "Feynman" };
  if (args.siteUrl) author.url = args.siteUrl;

  const questionObj: Json = {
    "@type": "Question",
    name: args.question,
    text: args.question,
    answerCount: 1,
    upvoteCount: 0,
    url: args.url,
    author,
    acceptedAnswer: {
      "@type": "Answer",
      text: answerText,
      upvoteCount: 0,
      url: args.url,
      author,
    },
  };
  if (args.dateCreated) {
    questionObj.dateCreated = args.dateCreated;
    (questionObj.acceptedAnswer as Json).dateCreated = args.dateCreated;
  }
  return dropNulls({
    "@context": "https://schema.org",
    "@type": "QAPage",
    mainEntity: questionObj,
  });
}

export interface InsightsArticleJsonldArgs {
  headline: string;
  description: string;
  url: string;
  aboutUrl: string;
  aboutType: "Book" | "Person";
  aboutName: string;
  siteUrl: string;
  dateModified?: string;
  insightCount?: number;
}

/** Schema.org/Article describing the aggregated insights page. */
export function insightsArticleJsonld(args: InsightsArticleJsonldArgs): Json {
  const out: Json = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: args.headline,
    description: args.description,
    url: args.url,
    author: { "@type": "Organization", name: "Feynman", url: args.siteUrl },
    publisher: { "@type": "Organization", name: "Feynman", url: args.siteUrl },
    about: {
      "@type": args.aboutType,
      name: args.aboutName,
      url: args.aboutUrl,
    },
  };
  if (args.dateModified) out.dateModified = args.dateModified;
  if (args.insightCount) out.wordCount = args.insightCount * 150;
  return dropNulls(out);
}

// ─── Capability detection (ported from seo.py detect_capabilities) ─────
//
// The Python original reads the `ai_books` row (total_words, outline,
// status). The JSON API only exposes the `agents` row, so this adapter
// works off agent.meta — which carries `outline`, `total_words`, and
// `chunk_count` for indexed books — and estimates word count from
// chunk_count (~250 words/chunk) when total_words is absent.

const READ_MIN_WORDS = 500;
const WORDS_PER_CHUNK = 250; // matches the index chunker's target size

export interface Capabilities {
  read: boolean;
  preview: boolean;
  chat: boolean;
}

export interface AgentMeta {
  author?: string;
  subtitle?: string;
  title?: string;
  description?: string;
  category?: string;
  chunk_count?: number;
  total_words?: number;
  outline?: { subtitle?: string; chapters?: Chapter[] } | null;
  status?: string;
  questions?: string[];
  [k: string]: unknown;
}

export interface AgentRow {
  id: string;
  name: string;
  type?: string;
  status?: string;
  source?: string;
  created_at?: string;
  meta?: AgentMeta;
}

/**
 * Decide which CTAs this book legitimately supports. Returns {read,
 * preview, chat}. Mirrors detect_capabilities but sourced from the agent
 * row (the only data the JSON API exposes for SSR).
 */
export function detectCapabilities(agent: AgentRow | null): Capabilities {
  if (!agent) return { read: false, preview: false, chat: false };
  const status = (agent.status || "").toLowerCase();
  if (["failed", "cancelled", "error"].includes(status)) {
    return { read: false, preview: false, chat: false };
  }

  const meta = agent.meta || {};
  const outline = meta.outline || null;
  const chapterCount = Array.isArray(outline?.chapters)
    ? outline!.chapters!.length
    : 0;
  const bookStatus = status; // agent status is the only status we have

  let totalWords = Number(meta.total_words || 0);
  if (!totalWords && meta.chunk_count) {
    totalWords = Number(meta.chunk_count) * WORDS_PER_CHUNK;
  }

  const agentType = (agent.type || "").toLowerCase();
  const isAiBook = agentType === "ai_book";

  // Read: enough body text AND structured enough to read linearly.
  const canRead =
    totalWords >= READ_MIN_WORDS &&
    (chapterCount > 0 ||
      isAiBook ||
      agentType === "upload" ||
      agentType === "url");

  // Preview: something to look at, but not a full read.
  const canPreview =
    (totalWords > 0 && totalWords < READ_MIN_WORDS) ||
    (bookStatus === "writing" && chapterCount > 0);

  // Chat: virtually always available (catalog stubs chat via RAG + LLM).
  const canChat = true;

  return { read: canRead, preview: canPreview, chat: canChat };
}

// ─── Data-fetch helpers (graceful degradation) ─────────────────────────

export interface BookData {
  agent: AgentRow;
  meta: AgentMeta;
  title: string;
  author: string;
  subtitle: string;
  description: string;
  category: string;
  chapters: Chapter[];
  totalWords: number;
}

/** Resolve the display author the way the legacy `_resolve_og_author` does. */
function resolveAuthor(agent: AgentRow): string {
  const meta = agent.meta || {};
  return (meta.author || agent.source || "").toString().trim();
}

/**
 * Fetch the agent row and normalize the book view-model. Returns null when
 * the agent is missing or the API is unreachable — callers should
 * notFound() on null.
 */
export async function getBookData(id: string): Promise<BookData | null> {
  let agent: AgentRow | null = null;
  try {
    agent = await get<AgentRow>(`/api/agents/${encodeURIComponent(id)}`);
  } catch {
    return null;
  }
  if (!agent || !agent.id) return null;

  const meta: AgentMeta = agent.meta || {};
  const outline = meta.outline || null;
  const subtitle = (outline?.subtitle || "").toString();
  const chapters = Array.isArray(outline?.chapters) ? outline!.chapters! : [];
  const title = (meta.title || agent.name || "Untitled").toString();
  const author = resolveAuthor(agent);
  let totalWords = Number(meta.total_words || 0);
  if (!totalWords && meta.chunk_count) {
    totalWords = Number(meta.chunk_count) * WORDS_PER_CHUNK;
  }

  return {
    agent,
    meta,
    title,
    author,
    subtitle,
    description: (meta.description || "").toString(),
    category: (meta.category || "").toString().trim(),
    chapters,
    totalWords,
  };
}

/** Fetch popular questions. Returns [] on any failure. */
export async function getQuestions(id: string): Promise<string[]> {
  try {
    const res = await get<{ questions?: string[] }>(
      `/api/agents/${encodeURIComponent(id)}/questions`,
    );
    return Array.isArray(res?.questions) ? res.questions.filter(Boolean) : [];
  } catch {
    return [];
  }
}

export interface SamplePassage {
  index: number;
  text: string;
}

interface ReadResponse {
  type?: string;
  chunks?: { index?: number; text?: string }[];
  paragraphs?: string[];
  chapters?: { number?: number; title?: string; content?: string }[];
  title?: string;
  subtitle?: string;
  author?: string;
  total_words?: number;
}

export interface BookReadMeta {
  title?: string;
  subtitle?: string;
  author?: string;
}

/**
 * Author + subtitle from the public /read endpoint.
 *
 * For AI-written books these live in the ai_books row, NOT the agent's
 * meta_json — so /api/agents (getBookData) returns source="ai_writer" with NO
 * subtitle, while /read returns the real "{creator} · AI" author + the book's
 * subtitle (exactly what the reader cover shows). The detail page already
 * fetches /read (getSamplePassages), so Next dedupes this within the request.
 * Empty object on failure → callers fall back to getBookData. Public,
 * edge-cached, no auth — crawler-safe (used by the OG route too).
 */
export async function getBookReadMeta(id: string): Promise<BookReadMeta> {
  try {
    const res = await get<ReadResponse>(
      `/api/public/book/${encodeURIComponent(id)}/read`,
    );
    return {
      title: (res?.title || "").trim() || undefined,
      subtitle: (res?.subtitle || "").trim() || undefined,
      author: (res?.author || "").trim() || undefined,
    };
  } catch {
    return {};
  }
}

/**
 * Fetch up to `count` sample passages for the "From the book" section.
 *
 * The /read endpoint shape varies by book type:
 *   - explicit `chunks[]` (if the API ever returns them),
 *   - `paragraphs[]` for reassembled regular books,
 *   - `chapters[].content` for AI-written books.
 * We coalesce whichever is present into leading SamplePassage objects.
 * Returns [] on any failure (catalog stubs / no content / API down).
 */
// Gutenberg / scan boilerplate that makes a useless "sample passage" if it
// leaks past the front-matter skip below.
const FRONT_MATTER_RE =
  /transcriber|project\s+gutenberg|gutenberg-tm|produced\s+by|distributed\s+proofread|all\s+rights\s+reserved|electronic\s+edition/i;

// Chunk/line splitting often cuts mid-sentence, so a sampled paragraph can open
// on a lowercase fragment ("…electrised that is foul. EXPERIMENT VI…"). Drop the
// leading partial sentence so the passage starts at a real boundary; if there's
// no clean break (or it would leave too little), keep the original.
function trimToSentenceStart(text: string): string {
  if (/^["“'([A-Z0-9]/.test(text)) return text; // already starts a sentence/quote/number
  const m = text.match(/[.?!]\s+(["“'(]?[A-Z])/);
  if (m && m.index !== undefined) {
    const rest = text.slice(m.index + m[0].length - m[1].length).trim();
    if (rest.length >= 60) return rest;
  }
  return text;
}

export async function getSamplePassages(
  id: string,
  count = 3,
): Promise<SamplePassage[]> {
  let res: ReadResponse | null = null;
  try {
    // Public, edge-cached read endpoint (serves ready books without auth).
    // The authed /api/agents/{id}/read is gated for the in-app reader, so the
    // SSR (no user cookie) must use the public mirror or it 401s and renders
    // a passage-less — and thus thin — book page.
    res = await get<ReadResponse>(
      `/api/public/book/${encodeURIComponent(id)}/read`,
    );
  } catch {
    return [];
  }
  if (!res) return [];

  const out: SamplePassage[] = [];

  if (Array.isArray(res.chunks) && res.chunks.length) {
    for (const c of res.chunks) {
      const text = (c.text || "").trim();
      if (text) out.push({ index: out.length, text });
      if (out.length >= count) break;
    }
    return out;
  }

  if (Array.isArray(res.paragraphs) && res.paragraphs.length) {
    const paras = res.paragraphs;
    // Skip front matter (transcriber's notes, title page, contents) — for a long
    // book the opening paragraphs are boilerplate that makes a poor, non-
    // representative sample. Start ~10% in, require real prose length, and drop
    // Gutenberg boilerplate; fall back to any substantive paragraph if empty.
    const start = Math.min(
      Math.floor(paras.length * 0.1),
      Math.max(paras.length - count, 0),
    );
    const pick = (from: number, minLen: number) => {
      for (let i = from; i < paras.length && out.length < count; i++) {
        const raw = (paras[i] || "").trim();
        if (raw.length < minLen) continue;
        if (FRONT_MATTER_RE.test(raw)) continue;
        out.push({ index: out.length, text: trimToSentenceStart(raw) });
      }
    };
    pick(start, 100);
    if (!out.length) pick(0, 40);
    return out;
  }

  if (Array.isArray(res.chapters) && res.chapters.length) {
    for (const ch of res.chapters) {
      const body = (ch.content || "").trim();
      if (!body) continue;
      // First paragraph of the chapter as a representative passage.
      const firstPara = body.split(/\n\n+/)[0]?.trim() || body;
      out.push({ index: out.length, text: firstPara });
      if (out.length >= count) break;
    }
  }

  return out;
}

export interface InsightCard {
  text: string;
  created_at: string;
}

/**
 * Fetch publishable AI insight cards for /book/{id}/insights.
 *
 * Uses the public, server-sanitized endpoint GET /api/agents/{id}/insights
 * (mirrors the legacy book_insights_page: list_assistant_messages_for_agent +
 * insights.select_publishable — PII-scrubbed, deduped, role=assistant only).
 * Returns 404 when the insights feature flag is off; we treat that (and any
 * failure) as "no insights" so the page renders its empty state.
 */
export async function getInsights(
  id: string,
  limit = 10,
): Promise<InsightCard[]> {
  try {
    const res = await get<{ insights?: InsightCard[] }>(
      `/api/agents/${encodeURIComponent(id)}/insights`,
    );
    const cards = Array.isArray(res?.insights) ? res.insights : [];
    return cards.slice(0, limit);
  } catch {
    return [];
  }
}

export interface BookConcept {
  term: string;
  note: string;
}
export interface BookOverview {
  overview: string;
  concepts: BookConcept[];
  grounded: boolean;
}

/**
 * Fetch the generated "About this book" overview + key concepts
 * (GET /api/agents/{id}/overview). On-demand generated + cached server-side;
 * returns null when empty/disabled/failed so the hub falls back to its
 * synthesized about-line. This is the Bucket-B content-density floor — it
 * fills on the first crawl of each book, no upfront batch.
 */
export async function getBookOverview(id: string): Promise<BookOverview | null> {
  try {
    const res = await get<BookOverview>(
      `/api/agents/${encodeURIComponent(id)}/overview`,
    );
    if (!res || !res.overview) return null;
    return {
      overview: res.overview,
      concepts: Array.isArray(res.concepts) ? res.concepts.filter((c) => c?.term && c?.note) : [],
      grounded: !!res.grounded,
    };
  } catch {
    return null;
  }
}

export interface QaPassage {
  chunk_index?: number;
  text: string;
}
export interface BookQa {
  question: string;
  answer: string;
  passages: QaPassage[];
}

/**
 * Fetch the grounded answer + supporting passages for one book question
 * (GET /api/agents/{id}/qa?question=…). Mirrors the legacy book_question_page.
 * Returns null on failure; the page then renders passages-only / empty state.
 */
export async function getBookQa(id: string, question: string): Promise<BookQa | null> {
  try {
    const res = await get<BookQa>(
      `/api/agents/${encodeURIComponent(id)}/qa?question=${encodeURIComponent(question)}`,
    );
    if (!res) return null;
    return {
      question: res.question || question,
      answer: res.answer || "",
      passages: Array.isArray(res.passages) ? res.passages : [],
    };
  } catch {
    return null;
  }
}

export interface RelatedBook {
  id: string;
  name: string;
  slug?: string;
  author?: string;
  type?: string;
}
export interface RelatedMind {
  id: string;
  name: string;
  slug?: string;
  era?: string;
  domain?: string;
  activity?: { count: number; last_seen?: string };
}

/**
 * Fetch related books + minds for a book (GET /api/agents/{id}/related).
 * Mirrors the cross-link sections of the legacy book_page. Returns empty
 * arrays on failure so the sections simply omit.
 */
export async function getRelatedForBook(
  id: string,
): Promise<{ books: RelatedBook[]; minds: RelatedMind[] }> {
  try {
    const res = await get<{ books?: RelatedBook[]; minds?: RelatedMind[] }>(
      `/api/agents/${encodeURIComponent(id)}/related`,
    );
    return {
      books: Array.isArray(res?.books) ? res.books : [],
      minds: Array.isArray(res?.minds) ? res.minds : [],
    };
  } catch {
    return { books: [], minds: [] };
  }
}

// ─── Small shared helpers for the pages/components ─────────────────────

/**
 * Truncate to maxChars on a word boundary with an ellipsis (port of the
 * rsplit(" ", 1) pattern used across seo.py renderers).
 */
export function truncateWords(text: string, maxChars: number): string {
  const t = (text || "").trim();
  if (t.length <= maxChars) return t;
  const cut = t.slice(0, maxChars);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > 0 ? cut.slice(0, lastSpace) : cut) + "…";
}

/** Clamp a meta description to ~200 chars on a word boundary. */
export function clampDescription(text: string, maxChars = 200): string {
  const t = (text || "").trim();
  if (t.length <= maxChars) return t;
  const cut = t.slice(0, maxChars - 3);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > 0 ? cut.slice(0, lastSpace) : cut) + "...";
}

/** Reading-time + chapter stats line (port of render_stats math). */
export function statsLine(totalWords: number, chapterCount: number): string {
  const bits: string[] = [];
  if (totalWords) {
    bits.push(`${totalWords.toLocaleString("en-US")} words`);
    bits.push(`~${Math.max(1, Math.floor(totalWords / 250))} min read`);
  }
  if (chapterCount) {
    bits.push(`${chapterCount} chapters`);
  }
  return bits.join(" · ");
}

/**
 * The canonical reader/chat URL for a book. Real Next path, no hash —
 * the new app routes /read/{id} (not the legacy SPA's /#/read/{id}).
 */
export function readerUrl(id: string): string {
  return `${SITE_URL}/read/${encodeURIComponent(id)}`;
}
