import type { Metadata } from "next";
import "@/styles/app.css";
// Loaded AFTER app.css: re-skins the product to macOS Tahoe Liquid Glass by
// overriding the design tokens + layering glass onto the control layer.
import "@/styles/liquid.css";
import ClientProviders from "@/components/providers/ClientProviders";

const SITE_DESCRIPTION =
  "An interactive knowledge network built on the world's most important books and great minds. Chat with any book, explore topics with AI-curated sources, and discuss ideas with simulated great thinkers.";

export const metadata: Metadata = {
  title: "Feynman — Chat with Books. Great Minds Join In.",
  description: SITE_DESCRIPTION,
  metadataBase: new URL("https://feynman.wiki"),
  // Default Open Graph / Twitter card for pages that don't set their own
  // (home, /library, /minds, /chats, etc.). Entity pages (book/mind) override
  // this with their own per-entity og:image. The default image is generated by
  // the Python backend at /api/og-image/default (crawlable per robots.txt).
  // NOTE: deliberately NO top-level `alternates.canonical` here — a layout-level
  // canonical would force every page to claim canonical="/" (duplicate-content
  // disaster). Pages self-canonicalize; book/mind set their own.
  openGraph: {
    type: "website",
    siteName: "Feynman",
    url: "https://feynman.wiki",
    title: "Feynman — Chat with Books. Great Minds Join In.",
    description: SITE_DESCRIPTION,
    images: [{ url: "/api/og-image/default", width: 1200, height: 630, alt: "Feynman" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Feynman — Chat with Books. Great Minds Join In.",
    description: SITE_DESCRIPTION,
    images: ["/api/og-image/default"],
  },
};

// Replicates the legacy theme-init trick (index.html): apply the saved theme
// class to <html> before first paint to avoid a flash of the wrong theme.
const THEME_INIT = `(function(){try{var t=localStorage.getItem('feynman-theme');if(t)document.documentElement.classList.add(t);}catch(e){}})();`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT }} />
      </head>
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
