"""Re-index existing book agents through Gutenberg.

Why this exists
---------------
Audit on 2026-05-26 found 912 of 920 book agents in production were
metadata stubs (0-4 chunks each) because the original catalog
discovery flow only had access to OpenLibrary / Google Books /
Wikipedia, none of which return full book text.

The Gutenberg integration (``app/core/sources_gutenberg.py``) added
later searches a local catalog of ~70K public-domain books and
fetches full text from gutenberg.org. This script walks the existing
agents and tries to upgrade each one's content via Gutenberg.

Expected impact
---------------
Per the Great Minds roster, roughly 20-50 books should have a
Gutenberg match (Marx, Smith, Darwin, Aristotle, Plato, Nietzsche,
Kant, Mill, Locke, Hobbes, Hume, Freud, Tolstoy, Dostoevsky, ...)
and become HIGH-tier (≥10 chunks, full text). Modern books stay LOW
or STUB because they aren't on Gutenberg (copyright).

Usage
-----
  python -m scripts.reindex_via_gutenberg                # full backfill
  python -m scripts.reindex_via_gutenberg --dry-run      # report what would change
  python -m scripts.reindex_via_gutenberg --limit 10     # cap at N
  python -m scripts.reindex_via_gutenberg --agent ID     # one specific agent
  python -m scripts.reindex_via_gutenberg --min-chunks 5 # only re-index agents below this

Required env vars
-----------------
  DATABASE_URL    Supabase pooler URL (same as the app).
  GEMINI_API_KEY  (or equivalent) — re-indexing generates embeddings
                  for the new chunks.

Properties
----------
- **Read-first, write-second.** ``--dry-run`` makes zero LLM calls
  and zero DB writes. Use it to size the backfill before committing.
- **Idempotent.** Re-running picks up any books that previously
  failed (e.g. transient HTTP error fetching from gutenberg.org).
  Already-upgraded books are skipped via the chunk-count gate.
- **Bounded cost.** Each successful re-index calls the embedder once
  per chunk. A typical Gutenberg book is ~500 chunks; at Gemini
  ``embedding-001`` rates this is well under \$0.01 per book. Full
  backfill of ~50 matched books is roughly \$0.50.
- **Per-agent atomic.** If a re-index crashes mid-book, that book
  stays in its previous state; the next run retries cleanly.
- **No catalog mutation.** This script never creates new agents,
  never renames, never deletes. It only adds chunks via the standard
  indexer pipeline.
"""
from __future__ import annotations

import argparse
import logging
import sys
import time
from typing import Any

from app.core import config  # noqa: F401 — loads env
from app.core.db import (
    count_chunks_batch,
    get_agent,
    get_conn,
    init_db,
    list_agents,
    probe_pgvector,
    _fetchall,
    _q,
)
import os as _os
from app.core.indexer import index_text
from app.core.sources_gutenberg import (
    fetch_gutenberg_content,
    search_gutenberg,
)

log = logging.getLogger("reindex_via_gutenberg")


def _resolve_author(agent: dict[str, Any]) -> str:
    """Pull a usable author string off the agent row. Catalog books
    store it under ``meta.author``; ai_books store it under
    ``meta.author`` or ``meta.creator_name``; uploads typically have
    no clean author."""
    meta = agent.get("meta") or {}
    if isinstance(meta, dict):
        return (meta.get("author") or meta.get("creator_name") or "").strip()
    return ""


def _eligible(
    agent: dict[str, Any], current_chunks: int, min_chunks: int,
) -> tuple[bool, str]:
    """Re-index is SAFETY-CRITICAL because it overwrites the agent's
    chunks via ``index_text(..., force=True)``. Only catalog-type
    agents are eligible: their existing chunks are just OL/GB
    metadata blurbs (which is what made them LOW/STUB tier in the
    first place), so overwriting with real Gutenberg text is a
    strict upgrade. Other types are protected:

      * ai_book: text was generated by the AI writer — overwriting
        would lose user-paid LLM output.
      * upload: text came from a user-uploaded PDF / TXT — overwriting
        would lose the user's content entirely.
      * url: text came from a URL the user explicitly imported —
        overwriting would silently replace the imported source.

    The agent_type guard is the hard line; the chunk-count gate is
    secondary (a catalog stub with already-substantial chunks
    probably went through the indexer once and should be left alone).
    """
    if agent.get("status") not in ("ready", "catalog"):
        return False, f"status={agent.get('status')!r}"
    if agent.get("type") != "catalog":
        # Only catalog stubs are safe to overwrite — see docstring
        return False, f"protected_type={agent.get('type')!r}"
    if current_chunks >= min_chunks:
        return False, f"already_has_{current_chunks}_chunks"
    return True, ""


def _process(
    agent: dict[str, Any], dry_run: bool, max_text_kb: int | None = None,
) -> tuple[str, str]:
    """Returns (verdict, message). verdict ∈ {SKIP_NO_MATCH, WOULD_UPGRADE,
    UPGRADED, FAILED}.

    ``max_text_kb`` caps the per-book text size to keep DB storage
    bounded — important on Supabase free tier where each chunk costs
    ~55KB (text + halfvec embedding + overhead). A 200KB cap yields
    ~170 chunks ≈ 9MB per book; full text for War-and-Peace-class
    books would be ~70MB each which blows the free-tier budget.
    """
    aid = agent["id"]
    name = agent.get("name") or ""
    author = _resolve_author(agent)

    match = search_gutenberg(name, author)
    if not match:
        return "SKIP_NO_MATCH", "no Gutenberg catalog match"

    if dry_run:
        return "WOULD_UPGRADE", (
            f"matched Gutenberg book_id={match['id']} "
            f"({match['title'][:50]!r} by {[a[:30] for a in match['authors'][:1]]})"
        )

    text = fetch_gutenberg_content(name, author)
    if not text:
        return "FAILED", f"matched book_id={match['id']} but text fetch returned empty"
    orig_chars = len(text)
    if max_text_kb is not None and orig_chars > max_text_kb * 1024:
        text = text[: max_text_kb * 1024]
        # Snap to a sentence boundary if we can — avoids cutting mid-word
        last_period = text.rfind(". ")
        if last_period > len(text) * 0.9:
            text = text[: last_period + 1]

    # index_text(replace_existing=True) deletes stale stub chunks AFTER
    # embeddings come back successfully — if the embedder 429s the agent
    # keeps its pre-existing chunks instead of getting wiped to zero.
    # See indexer.index_text docstring for the failure-mode reasoning.
    try:
        result = index_text(
            aid, text, update_status=True, force=True, replace_existing=True,
        )
    except Exception as exc:
        return "FAILED", f"index_text exception: {exc}"

    chunks = (result.get("chunk_count") if isinstance(result, dict) else None)
    cap_note = ""
    if max_text_kb is not None and orig_chars > max_text_kb * 1024:
        cap_note = f" (capped from {orig_chars:,} → {len(text):,})"
    return "UPGRADED", (
        f"Gutenberg book_id={match['id']}, "
        f"{len(text):,} chars{cap_note} → {chunks or '?'} chunks"
    )


def _priority_score(agent_id: str, mind_works_links: dict[str, int]) -> int:
    """Higher score = more important to upgrade first. Books referenced
    by more great-mind agents (via mind_works) are higher-leverage for
    SEO because they're the canonical works cited on mind pages."""
    return mind_works_links.get(agent_id, 0)


def _fetch_mind_works_counts() -> dict[str, int]:
    """Returns {agent_id: count_of_minds_that_reference_this_book}.
    Used for --priority ordering."""
    try:
        with get_conn() as conn:
            rows = _fetchall(conn, _q(
                "SELECT agent_id, COUNT(*) as n FROM mind_works GROUP BY agent_id"
            ))
            return {r["agent_id"]: int(r["n"]) for r in rows}
    except Exception:
        return {}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="Report what would change. Zero LLM calls, zero writes.")
    parser.add_argument("--limit", type=int, default=None,
                        help="Process at most N eligible agents.")
    parser.add_argument("--agent", type=str, default=None,
                        help="Process only this agent id.")
    parser.add_argument("--min-chunks", type=int, default=5,
                        help="Only re-index agents with fewer than this many chunks (default 5).")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Print per-skip detail.")
    parser.add_argument("--skip-init-db", action="store_true",
                        help="Skip init_db() — use when the schema is already established "
                             "(production). init_db can hang on pooled connections (pgbouncer) "
                             "when it tries to run idempotent migrations through transaction-mode pooling.")
    parser.add_argument("--max-text-kb", type=int, default=None,
                        help="Cap per-book Gutenberg text to N kilobytes before indexing. "
                             "Each KB of text becomes ~46 bytes in chunks table (text + halfvec). "
                             "Use 200 for ~9MB/book budget; 400 for ~18MB/book; omit for full text "
                             "(can be 70MB+ for War-and-Peace-class books).")
    parser.add_argument("--priority", action="store_true",
                        help="Process agents in priority order: books referenced by more great-mind "
                             "agents (via mind_works) go first. Use with --limit to backfill "
                             "highest-leverage books in the first batch.")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    print(
        f"--- reindex_via_gutenberg (dry_run={args.dry_run}, "
        f"min_chunks={args.min_chunks}, skip_init_db={args.skip_init_db}) ---",
        file=sys.stderr,
    )
    if not args.skip_init_db:
        init_db()

    # ``--skip-init-db`` dodges init_db()'s migration cascade (which hangs
    # on pgbouncer transaction-mode pooling), but that leaves
    # ``db._HAS_PGVECTOR`` at its False default, and ``add_chunks`` then
    # silently falls through to the legacy BYTEA-only write path. Probe
    # the column directly — read-only, pooler-safe — so the halfvec
    # write path is enabled regardless of which init mode the caller
    # chose. See db.probe_pgvector docstring.
    has_pgvec = probe_pgvector()
    print(f"pgvector write path: {'enabled' if has_pgvec else 'DISABLED'}",
          file=sys.stderr)

    if args.agent:
        a = get_agent(args.agent)
        if not a:
            print(f"agent not found: {args.agent}", file=sys.stderr)
            return 2
        targets = [a]
    else:
        targets = list(list_agents(limit=10000))

    chunk_counts = count_chunks_batch([a["id"] for a in targets])
    if args.priority:
        # Sort by mind_works link count desc — books that great minds
        # reference go first, so first batches upgrade the highest-SEO-
        # leverage pages (their mind page link targets become real
        # full-text books instead of metadata stubs).
        mw_counts = _fetch_mind_works_counts()
        targets.sort(key=lambda a: mw_counts.get(a["id"], 0), reverse=True)
        print(f"priority order: top agent has {mw_counts.get(targets[0]['id'], 0)} mind_works refs",
              file=sys.stderr)
    print(f"scanning {len(targets)} agents", file=sys.stderr)

    # Two-pass: pass 1 finds matchable agents (cheap — local catalog
    # search only, no fetch). Pass 2 does the actual fetch+index and
    # respects --limit on UPGRADED count (not skipped count). This
    # is the natural semantic: '--limit 5' should mean 'upgrade 5
    # books', not 'process 5 agents most of which won't match'.
    print("pass 1: scanning for matchable agents (no fetch)…", file=sys.stderr)
    matchable: list[dict[str, Any]] = []
    skipped = 0
    for agent in targets:
        cc = chunk_counts.get(agent["id"], 0)
        eligible, reason = _eligible(agent, cc, args.min_chunks)
        if not eligible:
            skipped += 1
            if args.verbose:
                print(f"  skip {agent['id'][:8]} {agent.get('name','')[:40]!r:<42} ({reason})", file=sys.stderr)
            continue
        # Cheap pre-check — search the local Gutenberg catalog. We
        # call _process with dry_run=True which short-circuits before
        # any HTTP fetch or DB write, returning WOULD_UPGRADE or
        # SKIP_NO_MATCH.
        verdict, msg = _process(agent, dry_run=True, max_text_kb=None)
        if verdict == "WOULD_UPGRADE":
            matchable.append(agent)
        if args.verbose:
            marker = "→" if verdict == "WOULD_UPGRADE" else "·"
            print(f"  {marker} {verdict:<14} {agent['id'][:8]} {agent.get('name','')[:50]!r}", file=sys.stderr)
    print(f"pass 1 done: {len(matchable)} matchable agents found", file=sys.stderr)

    # Pass 2 — actual fetch+index, with --limit applied to matchable list
    if args.limit is not None:
        matchable = matchable[: args.limit]
        print(f"limited to first {len(matchable)} for this batch", file=sys.stderr)
    if args.dry_run:
        # Dry run is already done — report and exit
        elapsed = time.time() - start_time if False else 0.0
        print(
            f"--- dry-run done: processed={len(matchable)} skipped={skipped} "
            f"would_upgrade={len(matchable)} no_match={len(targets) - skipped - len(matchable)} ---",
            file=sys.stderr,
        )
        return 0

    print(f"pass 2: fetching + indexing {len(matchable)} books (this is the slow part)…", file=sys.stderr)
    processed = upgraded = failed = 0
    start = time.time()
    for agent in matchable:
        processed += 1
        verdict, msg = _process(agent, dry_run=False, max_text_kb=args.max_text_kb)
        marker = "✓" if verdict == "UPGRADED" else "✗"
        print(
            f"  {marker} {verdict:<14} {agent['id'][:8]} "
            f"{agent.get('name','')[:55]!r:<57} — {msg}",
            file=sys.stderr,
        )
        if verdict == "UPGRADED":
            upgraded += 1
        elif verdict == "FAILED":
            failed += 1

    elapsed = time.time() - start
    print(
        f"--- done in {elapsed:.1f}s: processed={processed} "
        f"upgraded={upgraded} failed={failed} skipped={skipped} ---",
        file=sys.stderr,
    )
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
