"""Re-index existing book agents through Gutenberg.

Why this exists
---------------
Audit on 2026-05-26 found 912 of 920 book agents in production were
metadata stubs (0-4 chunks each) because the original catalog
discovery flow only had access to OpenLibrary / Google Books /
Wikipedia, none of which return full book text.

The Gutenberg integration (``app/core/sources_gutenberg.py``) added
later searches a local catalog of ~70K public-domain books and
fetches full text from gutenberg.org. This script walks the existing
agents and tries to upgrade each one's content via Gutenberg.

Expected impact
---------------
Per the Great Minds roster, roughly 20-50 books should have a
Gutenberg match (Marx, Smith, Darwin, Aristotle, Plato, Nietzsche,
Kant, Mill, Locke, Hobbes, Hume, Freud, Tolstoy, Dostoevsky, ...)
and become HIGH-tier (≥10 chunks, full text). Modern books stay LOW
or STUB because they aren't on Gutenberg (copyright).

Usage
-----
  python -m scripts.reindex_via_gutenberg                # full backfill
  python -m scripts.reindex_via_gutenberg --dry-run      # report what would change
  python -m scripts.reindex_via_gutenberg --limit 10     # cap at N
  python -m scripts.reindex_via_gutenberg --agent ID     # one specific agent
  python -m scripts.reindex_via_gutenberg --min-chunks 5 # only re-index agents below this

Required env vars
-----------------
  DATABASE_URL    Supabase pooler URL (same as the app).
  GEMINI_API_KEY  (or equivalent) — re-indexing generates embeddings
                  for the new chunks.

Properties
----------
- **Read-first, write-second.** ``--dry-run`` makes zero LLM calls
  and zero DB writes. Use it to size the backfill before committing.
- **Idempotent.** Re-running picks up any books that previously
  failed (e.g. transient HTTP error fetching from gutenberg.org).
  Already-upgraded books are skipped via the chunk-count gate.
- **Bounded cost.** Each successful re-index calls the embedder once
  per chunk. A typical Gutenberg book is ~500 chunks; at Gemini
  ``embedding-001`` rates this is well under \$0.01 per book. Full
  backfill of ~50 matched books is roughly \$0.50.
- **Per-agent atomic.** If a re-index crashes mid-book, that book
  stays in its previous state; the next run retries cleanly.
- **No catalog mutation.** This script never creates new agents,
  never renames, never deletes. It only adds chunks via the standard
  indexer pipeline.
"""
from __future__ import annotations

import argparse
import logging
import sys
import time
from typing import Any

from app.core import config  # noqa: F401 — loads env
from app.core.db import (
    count_chunks_batch,
    get_agent,
    init_db,
    list_agents,
)
from app.core.indexer import index_text
from app.core.sources_gutenberg import (
    fetch_gutenberg_content,
    search_gutenberg,
)

log = logging.getLogger("reindex_via_gutenberg")


def _resolve_author(agent: dict[str, Any]) -> str:
    """Pull a usable author string off the agent row. Catalog books
    store it under ``meta.author``; ai_books store it under
    ``meta.author`` or ``meta.creator_name``; uploads typically have
    no clean author."""
    meta = agent.get("meta") or {}
    if isinstance(meta, dict):
        return (meta.get("author") or meta.get("creator_name") or "").strip()
    return ""


def _eligible(
    agent: dict[str, Any], current_chunks: int, min_chunks: int,
) -> tuple[bool, str]:
    """Re-index is SAFETY-CRITICAL because it overwrites the agent's
    chunks via ``index_text(..., force=True)``. Only catalog-type
    agents are eligible: their existing chunks are just OL/GB
    metadata blurbs (which is what made them LOW/STUB tier in the
    first place), so overwriting with real Gutenberg text is a
    strict upgrade. Other types are protected:

      * ai_book: text was generated by the AI writer — overwriting
        would lose user-paid LLM output.
      * upload: text came from a user-uploaded PDF / TXT — overwriting
        would lose the user's content entirely.
      * url: text came from a URL the user explicitly imported —
        overwriting would silently replace the imported source.

    The agent_type guard is the hard line; the chunk-count gate is
    secondary (a catalog stub with already-substantial chunks
    probably went through the indexer once and should be left alone).
    """
    if agent.get("status") not in ("ready", "catalog"):
        return False, f"status={agent.get('status')!r}"
    if agent.get("type") != "catalog":
        # Only catalog stubs are safe to overwrite — see docstring
        return False, f"protected_type={agent.get('type')!r}"
    if current_chunks >= min_chunks:
        return False, f"already_has_{current_chunks}_chunks"
    return True, ""


def _process(
    agent: dict[str, Any], dry_run: bool,
) -> tuple[str, str]:
    """Returns (verdict, message). verdict ∈ {SKIP_NO_MATCH, WOULD_UPGRADE,
    UPGRADED, FAILED}."""
    aid = agent["id"]
    name = agent.get("name") or ""
    author = _resolve_author(agent)

    match = search_gutenberg(name, author)
    if not match:
        return "SKIP_NO_MATCH", "no Gutenberg catalog match"

    if dry_run:
        return "WOULD_UPGRADE", (
            f"matched Gutenberg book_id={match['id']} "
            f"({match['title'][:50]!r} by {[a[:30] for a in match['authors'][:1]]})"
        )

    text = fetch_gutenberg_content(name, author)
    if not text:
        return "FAILED", f"matched book_id={match['id']} but text fetch returned empty"

    # Reindex — index_text replaces existing chunks for the agent
    try:
        result = index_text(aid, text, update_status=True, force=True)
    except Exception as exc:
        return "FAILED", f"index_text exception: {exc}"

    chunks = result.get("chunks") if isinstance(result, dict) else None
    return "UPGRADED", (
        f"Gutenberg book_id={match['id']}, "
        f"{len(text):,} chars → {chunks or '?'} chunks"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="Report what would change. Zero LLM calls, zero writes.")
    parser.add_argument("--limit", type=int, default=None,
                        help="Process at most N eligible agents.")
    parser.add_argument("--agent", type=str, default=None,
                        help="Process only this agent id.")
    parser.add_argument("--min-chunks", type=int, default=5,
                        help="Only re-index agents with fewer than this many chunks (default 5).")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Print per-skip detail.")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    print(
        f"--- reindex_via_gutenberg (dry_run={args.dry_run}, "
        f"min_chunks={args.min_chunks}) ---",
        file=sys.stderr,
    )
    init_db()

    if args.agent:
        a = get_agent(args.agent)
        if not a:
            print(f"agent not found: {args.agent}", file=sys.stderr)
            return 2
        targets = [a]
    else:
        targets = list(list_agents(limit=10000))

    chunk_counts = count_chunks_batch([a["id"] for a in targets])
    print(f"scanning {len(targets)} agents", file=sys.stderr)

    processed = upgraded = would = no_match = failed = skipped = 0
    start = time.time()
    for agent in targets:
        cc = chunk_counts.get(agent["id"], 0)
        eligible, reason = _eligible(agent, cc, args.min_chunks)
        if not eligible:
            skipped += 1
            if args.verbose:
                print(f"  skip {agent['id'][:8]} {agent.get('name','')[:40]!r:<42} ({reason})", file=sys.stderr)
            continue
        if args.limit is not None and processed >= args.limit:
            break
        processed += 1
        verdict, msg = _process(agent, dry_run=args.dry_run)
        marker = {
            "UPGRADED": "✓",
            "WOULD_UPGRADE": "→",
            "SKIP_NO_MATCH": "·",
            "FAILED": "✗",
        }.get(verdict, "?")
        print(
            f"  {marker} {verdict:<14} {agent['id'][:8]} "
            f"{agent.get('name','')[:55]!r:<57} — {msg}",
            file=sys.stderr,
        )
        if verdict == "UPGRADED":
            upgraded += 1
        elif verdict == "WOULD_UPGRADE":
            would += 1
        elif verdict == "FAILED":
            failed += 1
        else:
            no_match += 1

    elapsed = time.time() - start
    summary_parts = [f"processed={processed}", f"skipped={skipped}"]
    if args.dry_run:
        summary_parts.append(f"would_upgrade={would}")
    else:
        summary_parts.append(f"upgraded={upgraded}")
        summary_parts.append(f"failed={failed}")
    summary_parts.append(f"no_match={no_match}")
    print(
        f"--- done in {elapsed:.1f}s: " + " ".join(summary_parts) + " ---",
        file=sys.stderr,
    )
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
